### ISSUE TITLE
Paths do not work on all OS

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#1]
Hi, as part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1868) I'll open some small 'bug' issues and later one with more comments. 

The first one is that the way you join paths, e.g, in the `examples.py` does not work on all operating systems. It would be better if you use an OS agnostic way (`os.path.join`).

**Comment by kjappelbaum** [comment]
Somewhat related, I do not know if it is good to hard code the file separator without mentioning it (but there might also be good reasons for doing so). E.g., here https://github.com/1mikegrn/libRL-package/blob/3596a1530dd423e46748e62f14f2f06378099a06/libRL/refactoring.py#L91

I often see files that have the ending `csv` put use `tsv` formatting. Pandas seems to be good in figuring it out automatically.

**Comment by kjappelbaum** [comment]
Also 'Times New Roman' is [not available on e.g. Linux by default](https://github.com/1mikegrn/libRL-package/blob/d7a0b7b8cf35c56c0e797429fe14fc31c941a303/libRL/quick_graphs.py#L32). This might cause minor issues 

https://github.com/1mikegrn/libRL-package/blob/d7a0b7b8cf35c56c0e797429fe14fc31c941a303/libRL/quick_graphs.py#L32

But I see that you have "warnings" in this module that it is primarily for you.

**Comment by mgdotdev** [comment]
> The first one is that the way you join paths, e.g, in the `examples.py` does not work on all operating systems. It would be better if you use an OS agnostic way (`os.path.join`).

- I've gone ahead and edited the example.py file to make use of path.join as the method for concatenating directory strings for that initial test.

> I do not know if it is good to hard code the file separator without mentioning it (but there might also be good reasons for doing so)

- This was an attempt to make explicit to readers that the library expected enforcement of the 'comma' in .csv for when an error was thrown, though now I notice that even with the sep=',' command, if you give it tabbed data, it'll handle the import the same. What I've done to remedy this issue of dealing with .tsv formatted .csv files is to import the file with read_csv, and if the column shape is 1 and a row therein is a string which contains "\t", redo the import with sep = '\t'.

> 'Times New Roman' is [not available on e.g. Linux by default](https://github.com/1mikegrn/libRL-package/blob/d7a0b7b8cf35c56c0e797429fe14fc31c941a303/libRL/quick_graphs.py#L32). This might cause minor issues

- updated the rcParams for cross-compatibility. Still want it to generally work for everyone, just want to avoid formatting complaints; if one person wants the z scale to line up differently than someone else, or have a different color scheme, etc. But ya, rcParams should still work cross-platform for the generic user, so having a font that works for the generic user is a worthwhile patch. Appreciate you pointing that out.

**Comment by kjappelbaum** [comment]
I feel that there are still some paths that could be handled a bit more elegant, e.g. https://github.com/1mikegrn/libRL/blob/7c9342497b424e9ff5d03ab9fddfbd8816e4404f/libRL/quick_graphs.py#L162

**Comment by mgdotdev** [comment]
fixed the image paths

**Comment by kjappelbaum** [comment]
Thanks, closing the issue.
