### ISSUE TITLE
Tests could be more fine-grained and automatized 

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#4]
Hi, again for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1868). 

I saw that you have a test case for the code, which is great! If you want to improve on that you can write unit tests that test each (relevant) function (this makes it easier for new contributors to see where exactly they break your code) and run those tests automatically, e.g. with [pytest](https://pytest.org) on different platforms using e.g. [travis](https://travis-ci.org) or [azure pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python).

**Comment by mgdotdev** [comment]
I'll look into travis/pytest integration in the future, but for now I added a bit to the libRL_test so to provide full test coverage of the library.

**Comment by kjappelbaum** [comment]
Yes, automated testing with coverage report with a badge on the README would be useful. And testing the addition of test would be could (might be nicer to keep them separate to track down what fails. But the project is small so it doesn't matter than much). 

But I still do not know if just checking the best test case.

**Comment by mgdotdev** [comment]
Okay, was finally able to get all that working haha.

Added travis-CI integration and documentation through sphinx.

**Comment by kjappelbaum** [comment]
Great, closing this issue now.
