### ISSUE TITLE
Contribution guide is missing

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#5]
Another point for the [review for JOSS](https://github.com/openjournals/joss-reviews/issues/1868): You should probably add a contribution guide. See the [Github documentation](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors).

**Comment by mgdotdev** [comment]
Added a contributing.md file

**Comment by 1mikegrn** [comment]
sorry contributing.md

**Comment by kjappelbaum** [comment]
Great, closing it.
