### ISSUE TITLE
Documentation refactoring suggestions

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#6]
Again for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1868).
I like that you use sphinx and readthedocs for the documentation and have a lot of comments and docstrings.

One idea for improvement of the documentation would be to first give some more introduction and walk the reader through one example (show input, output, reference to theory) and then have some automatically generated API documentation ([sphinx.ext.napoleon](https://sphinxcontrib-napoleon.readthedocs.io/))  better separated from the installation and examples.

**Comment by kjappelbaum** [comment]
A further suggestions, that might be useful/make your life easier, is that you could add the docs directly to this repository (as a 'docs' subdirectory) and then [automatically trigger](https://acctestdocs.readthedocs.io/en/latest/webhooks.html) a rebuild (of the API documentation) if you push here.

**Comment by mgdotdev** [comment]
I've added an [examples](https://1mikegrn.github.io/DocSite/examples/) page at the DocSite that runs through an example calculation, and added an [Overview](https://1mikegrn.github.io/DocSite/overview/) section as well.

**Comment by kjappelbaum** [comment]
Nice improvement!

**Comment by kjappelbaum** [comment]
I think the checklist requirements are fulfilled. Still, for the users it might be less confusing if the documentation for separate projects is kept separate. Also, I think using Napoleon would help the sphinx site.
