### ISSUE TITLE
Example suggestions

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#7]
Here's one more issue for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1868). 

You have an example and it seems to work (besides the path issue). To make it even better you can consider having some more comments on it (e.g., a section in the docs that also shows the output plots one should find in the end) or even a Jupyter notebook with plots and markdown fields that describe what happens (and which can run on [binder](https://mybinder.org)) to show people what the code can do without them having to install the package.

**Comment by mgdotdev** [comment]
I added some comments and references to the DocSite, as well as changed the data source to grab data from the GitHub repository directly so we don't need to worry about path issues. I'm currently looking into hosting jupyter notebooks and binder but atm I think the site and example files should be sufficient.

**Comment by kjappelbaum** [comment]
Nice improvement! I do not think that Jupyter/Binder are requirements, but they would be nice if you want the library to be widely used.
