### ISSUE TITLE
JOSS review general comments

### ISSUE THREAD

**Issue by kjappelbaum** [1mikegrn/libRL#8]
Hi, just some general comments on your package, to summarize [my review](https://github.com/openjournals/joss-reviews/issues/1868). I'm not an expert in RAMs  but your package seems to be useful for your community and the software paper does its job in summarizing this need and you also highlight your previous works in it. It also seems to work, besides the minor [path issue](https://github.com/1mikegrn/libRL-package/issues/1).

I think the major points that would make it more user-friendly is to add some verbosity to an examples (see issue https://github.com/1mikegrn/libRL-package/issues/7 or https://github.com/1mikegrn/libRL-package/issues/6). You could even think about adding an installable command line interface as entry point, e.g. using [click](https://palletsprojects.com/p/click/) to make running the analysis a one-liner (at least for the next release). For developer friendliness, you can have a look at some of [output of pylint or prospector](https://github.com/1mikegrn/libRL-package/issues/3) beyond adding the  [contribution guidelines](https://github.com/1mikegrn/libRL-package/issues/5).

There are some issues that I couldn't check (yet) on the review checklist like [automatic tests](https://github.com/1mikegrn/libRL-package/issues/4), [contribution guidelines](https://github.com/1mikegrn/libRL-package/issues/5) and the [licence](https://github.com/1mikegrn/libRL-package/issues/2). But they seem to be relatively easy to fix.
You might also consider adding your package to pypi.

**Comment by mgdotdev** [comment]
First off, thank you for taking the time to review this software, I'm looking forward to reading your report and addressing the issues raised accordingly.

I'll comment/address each issue in the thread where it was raised, and then once all the points have been addressed/fixed in the library I'll push the update up to GitHub and comment again here.

**Comment by mgdotdev** [comment]
Actually now that I'm thinking about it, I'll probably periodically push instances to Git throughout the editing process so I can easily pull the library down to my Linux VM for cross-platform testing, but I'll be sure to respond here a final time once I've addressed all the comments.

**Comment by kjappelbaum** [comment]
just let me know if something is unclear, or I can support you. Many of the comments are just general suggestions for improvement which might make the package a bit nicer.

**Comment by mgdotdev** [comment]
I think that I've addressed all of the issues presented to an acceptable degree - if you agree, feel free to close the issue raised, or if you find that changes are still necessary, let me know what needs to be further addressed.

**Comment by kjappelbaum** [comment]
I think I'm fine now with most points and close this issue.

**Comment by kjappelbaum** [comment]
Just a minor point. If you want to keep the acknowledgment in the paper, my name is Kevin M. Jablonka ;)

**Comment by mgdotdev** [comment]
Haha thanks for the notice; updated accordingly.
